version: "3"
services:
    node:
        image: node:18.12.1-alpine
        expose:
            - "3001"
        ports:
            - "3001:3001"
        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis
            - rabbitmq
        command: npm start

    mongo:
        image: "mvertes/alpine-mongo"

    redis:
        image: "redis:6.2.1-alpine"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
